version: "3.9"

services:
  main:
    networks:
      - main
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8999:8000
    depends_on:
      - postgres
      - redis
    restart: on-failure
  postgres:
    image: postgres:13-alpine
    networks:
      - main
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=nft_user
      - POSTGRES_PASSWORD=nft_password
      - POSTGRES_DB=nft_database
  redis:
    image: redis
    networks:
      - main

networks:
  main:
    external: true

volumes:
  postgres:
