version: "3.9"

services:
  postgres:
    image: library/postgres:13-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - main
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "main"
    ports:
    - 5432:5432
  main:
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - main
    depends_on:
      - postgres
    volumes:
    - ./data/:/main/data


volumes:
  postgres:

networks:
  main: