version: "3.9"

services:
  mongo:
    image: mongo
    volumes:
      - mongo:/data/db
    networks:
      - main
    environment:
      MONGO_INITDB_DATABASE: "main"
    ports:
    - 27017:27017
  main:
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - main
    depends_on:
      - mongo
    volumes:
    - ./data/:/main/data


volumes:
  mongo:
    external: true

networks:
  main: